apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/server
#  - github.com/utilitywarehouse/kube-applier//manifests/base/server?ref=3.3.1
  - ../base/client
#  - github.com/utilitywarehouse/kube-applier//manifests/base/client?ref=3.3.1

resources:
  - kube-applier-ingress.yaml
  - waybill.yaml

patchesStrategicMerge:
# generic patch to specify environment/namespaces
  - kube-applier-patch.yaml

secretGenerator:
# ssh key to clone the "root" kubernetes manifests repository, used by git-sync
  - name: ssh
    type: Opaque
    files:
      - ssh=secrets/ssh
      - known_hosts=resources/known_hosts

# strongbox keyring is used to decrypt Secrets in this namespace
  - name: kube-applier-strongbox-keyring
    type: Opaque
    files:
      - .strongbox_keyring=secrets/strongbox-keyring
    options:
      disableNameSuffixHash: true
